### ISSUE TITLE
Decorators fail in sortier-vscode 1.0.9

### ISSUE THREAD

**Issue by peterbe** [snowcoders/sortier-vscode#18]
I *just* installed sortier-vscode in my vscode and ran `Sortier: Run` on a file with decorators. 

It failed. After it failed, I switched back to the tab with the Extension install. To show what I had installed. 
<img width="1616" alt="screen shot 2018-09-21 at 11 26 01 am" src="https://user-images.githubusercontent.com/26739/45890702-9c00b600-bd91-11e8-835a-56490c9bdcff.png">

According to this projects [package.json](https://github.com/snowcoders/sortier-vscode/blob/e73f00d976ad1f922b008e4f337d9259d6476b82/package.json#L62) it depends on the latest version of `sortier` which [supposedly supports decorators](https://github.com/snowcoders/sortier/issues/108#issuecomment-423394267)

**Comment by peterbe** [comment]
Relevant: https://github.com/snowcoders/sortier/issues/108#issuecomment-423575240

**Comment by k2snowman69** [comment]
Just released sortier-vscode to 1.0.10 which should have the decorators fix for javascript. Just updated the plugin and tried it on the code you provided in https://github.com/snowcoders/sortier/issues/108#issuecomment-423575240 by pasting it in a file named `test.js` and everything seemed to sort correctly.

If you don't mind giving it a second shot and closing this out if it works for you as well that would be great!

**Comment by k2snowman69** [comment]
Resolved as mentioned here:
https://github.com/snowcoders/sortier/issues/108#issuecomment-423575240
