### ISSUE TITLE
Sortier flips default import

### ISSUE THREAD

**Issue by royderksroute42** [snowcoders/sortier-vscode#20]
Hi there,

it seems i've encountered a problem.
Mainly that, when i use sortier, it flips the React and { Component } import.

`import React, { Component } from 'react';`

Turns into 

`import Component, { React } from 'react';`

Sortier 1.0.10
VSCode 1.27.2

**Comment by royderksroute42** [comment]
It doesn't do this when using a flow type `import React, { type Element } from 'react';`

`import React, { Component, Props } from 'react'`;   
into .   
`import Component, { Props, React } from 'react';`

**Comment by k2snowman69** [comment]
Reproduced locally with both typescript and flow-type, looking into the fix now

**Comment by k2snowman69** [comment]
https://github.com/snowcoders/sortier/issues/120

**Comment by k2snowman69** [comment]
And verified with the version on the marketplace. Thanks for opening the bug, let me know if there are any other bugs or features you would like!

**Comment by k2snowman69** [comment]
Please feel free to close this bug after you verify yourself :-)

**Comment by royderksroute42** [comment]
Thank you for the fast fix! It is indeed fixed. Closing this issue.
