### ISSUE TITLE
Support for sortier 3.x

### ISSUE THREAD

**Issue by jpaas** [snowcoders/sortier-vscode#219]
When a project is upgraded to sortier 3.x, the extension starts failing with:
`Sortier threw an error: formatFunc is not a function`

**Comment by k2snowman69** [comment]
sortier@v3 isn't backwards compatible with sortier@v2 and we have a [pull request](https://github.com/snowcoders/sortier-vscode/pull/217) already tracking this break.

Hope to have a new version of the plugin out tonight

**Comment by jpaas** [comment]
Thanks @k2snowman69 !

**Comment by k2snowman69** [comment]
Just published `sortier-vscode@1.2.4` mind giving it a try?

**Comment by k2snowman69** [comment]
Just FYI, there did seem to be some issue updating on OSX where it didn't pick up the new version automatically and I had to update it manually myself. My windows box was fine weirdly...

**Comment by jpaas** [comment]
Thanks @k2snowman69 it worked for me
