### ISSUE TITLE
onSave no longer working

### ISSUE THREAD

**Issue by jpaas** [snowcoders/sortier-vscode#489]
Recently onSave has stopped working but I can still manually run sortier and it works. Is there any way of debugging this?

I am running v1.3.0 with VSCode 1.52.1

**Comment by k2snowman69** [comment]
Whoops, probably tied to the unsaved file fix. I'll dig into this tonight.

**Comment by k2snowman69** [comment]
Released 1.3.1 - Can you verify on your end?

**Comment by jpaas** [comment]
Fixed! Thanks @k2snowman69
