### ISSUE TITLE
Feature request: exclude files

### ISSUE THREAD

**Issue by jpaas** [snowcoders/sortier-vscode#77]
It would be nice to exclude some files. e.g. I want to sort on save for JSON files, but not package.json.

**Comment by k2snowman69** [comment]
The CLI allows you to provide a globby pattern as the argument to say what should or should not be sorted of which I've found pretty flexible so far. Maybe it could be as simple as adding an "include" and/or "exclude" property? How does that sound?

**Comment by k2snowman69** [comment]
Also just as an FYI, I'm pretty booked for the next week or two but if you're willing to open a pull request and test it I'd be more than happy to merge and publish it. Just be sure to give yourself credit via the changelog :-)

**Comment by jpaas** [comment]
Thanks @k2snowman69.  Include and exclude are exactly what I was hoping for. I'm also pretty jammed at the moment, but I'll try to find some time.

**Comment by k2snowman69** [comment]
Just a heads up, chatting with @TikiTDO we thought moving file exclusion from the vscode plugin to the root sortier npm package along with adding a .sortierignore customization file would be more flexible and apply to CI and other automated tools that do not use vs code.

**Comment by k2snowman69** [comment]
Just released sortier 2.6.0 which fixes this for the cli... however when running it from the vscode plugin, it seems the ignore file is attempting to load from the wrong location (the execution path of vs code, not the workspace running) which results in the file still being sorted.

**Comment by k2snowman69** [comment]
Sortier 2.6.1 fixed the previous issue by basing the search path of the sortierignore file on the file being sorted (which should also help for workspace executions with multiple layers of sortierignore files)
#126

**Comment by k2snowman69** [comment]
Released 1.2.3 so you will either need the following combinations:
 - Just sortier-vscode@1.2.3 + no sortier installed in the current project or parent project
 - Just sortier-vscode@1.2.* + sortier@2.6.1
